#!/usr/bin/env bash
#Double the number of webservers
sudo apt update
sudo apt install haproxy -y
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver server1 18.207.1.87:80 check\n\tserver server2 52.206.189.175:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
