#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
counter=0
while ((counter++<10)); do
    if [[ $counter -eq 8 ]]; then
        echo "bad luck"
    elif [[ $counter -eq 4 ]]; then
        echo "good luck"
    else
        echo "Best School"
    fi
done
