#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
hour=-1
minute=1
while ((hour++<12)); do
    echo "Hour: $hour"
    minute=0
    while ((minute++<59)); do
    echo $minute
    done
done
