#!/usr/bin/env bash
# This script
sudo cp /etc/hosts ~/hosts.new
sudo sed -i '$ a\127.0.0.2 localhost' ~/hosts.new
sudo sed -i '$ a\8.8.8.8 facebook.com' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
